//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat.MessengerWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://messenger/", ConfigurationName="MessengerWS.MessengerItf")]
    public interface MessengerItf {
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://messenger/MessengerItf/messengerRequest", ReplyAction="http://messenger/MessengerItf/messengerResponse")]
        Chat.MessengerWS.messengerResponse messenger(Chat.MessengerWS.messengerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://messenger/MessengerItf/messengerRequest", ReplyAction="http://messenger/MessengerItf/messengerResponse")]
        System.Threading.Tasks.Task<Chat.MessengerWS.messengerResponse> messengerAsync(Chat.MessengerWS.messengerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class messengerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="messenger", Namespace="http://messenger/", Order=0)]
        public Chat.MessengerWS.messengerRequestBody Body;
        
        public messengerRequest() {
        }
        
        public messengerRequest(Chat.MessengerWS.messengerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class messengerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public messengerRequestBody() {
        }
        
        public messengerRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class messengerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="messengerResponse", Namespace="http://messenger/", Order=0)]
        public Chat.MessengerWS.messengerResponseBody Body;
        
        public messengerResponse() {
        }
        
        public messengerResponse(Chat.MessengerWS.messengerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class messengerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public messengerResponseBody() {
        }
        
        public messengerResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MessengerItfChannel : Chat.MessengerWS.MessengerItf, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessengerItfClient : System.ServiceModel.ClientBase<Chat.MessengerWS.MessengerItf>, Chat.MessengerWS.MessengerItf {
        
        public MessengerItfClient() {
        }
        
        public MessengerItfClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessengerItfClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessengerItfClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessengerItfClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chat.MessengerWS.messengerResponse Chat.MessengerWS.MessengerItf.messenger(Chat.MessengerWS.messengerRequest request) {
            return base.Channel.messenger(request);
        }
        
        public string messenger(string arg0) {
            Chat.MessengerWS.messengerRequest inValue = new Chat.MessengerWS.messengerRequest();
            inValue.Body = new Chat.MessengerWS.messengerRequestBody();
            inValue.Body.arg0 = arg0;
            Chat.MessengerWS.messengerResponse retVal = ((Chat.MessengerWS.MessengerItf)(this)).messenger(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Chat.MessengerWS.messengerResponse> Chat.MessengerWS.MessengerItf.messengerAsync(Chat.MessengerWS.messengerRequest request) {
            return base.Channel.messengerAsync(request);
        }
        
        public System.Threading.Tasks.Task<Chat.MessengerWS.messengerResponse> messengerAsync(string arg0) {
            Chat.MessengerWS.messengerRequest inValue = new Chat.MessengerWS.messengerRequest();
            inValue.Body = new Chat.MessengerWS.messengerRequestBody();
            inValue.Body.arg0 = arg0;
            return ((Chat.MessengerWS.MessengerItf)(this)).messengerAsync(inValue);
        }
    }
}
